//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HydrologieTablet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HydrologieTablet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRY TO BEAT THE AI IN HYDROLOGY.
        /// </summary>
        public static string ai_screen_game_eng {
            get {
                return ResourceManager.GetString("ai_screen_game_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHLAG DIE KI IN DER HYDROLOGIE.
        /// </summary>
        public static string ai_screen_game_ger {
            get {
                return ResourceManager.GetString("ai_screen_game_ger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHO GROWS THE MOST TOMATOES?.
        /// </summary>
        public static string game_headline_eng {
            get {
                return ResourceManager.GetString("game_headline_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WER ERNTET DIE MEISTEN TOMATEN?.
        /// </summary>
        public static string game_headline_ger {
            get {
                return ResourceManager.GetString("game_headline_ger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game, you can reduce the usual water consumption
        ///for the cultivation of tomato plants by using targeted watering.
        ///This strategy decreases agricultural water consumption by
        ///almost 50 per cent! Divide the 300 millimetres of available
        ///water between 15 weeks and try to achieve the highest yield in
        ///a tomato field..
        /// </summary>
        public static string game_text_eng_end {
            get {
                return ResourceManager.GetString("game_text_eng_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to beat the AI in
        ///Hydrology.
        /// </summary>
        public static string game_text_eng_gamename {
            get {
                return ResourceManager.GetString("game_text_eng_gamename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achieving high yields with little water is not easy. In the
        ///course of their growth, plants react differently to drought
        ///stress, weather, and soil conditions. In the.
        /// </summary>
        public static string game_text_eng_start {
            get {
                return ResourceManager.GetString("game_text_eng_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to den üblichen
        ///Wasserverbrauch bei der Kultivierung von Tomatenpflanzen
        ///durch gezieltes Gießen senken. Der Landwirtschaft ermöglicht
        ///diese Strategie, den Wasserverbrauch nahezu zu halbieren!
        ///Teile die 300 Millimeter verfügbares Wasser in zehn
        ///Wassergaben über 15 Wochen auf und versuche, auf einem
        ///Tomatenfeld den höchsten Ertrag zu erreichen..
        /// </summary>
        public static string game_text_ger_end {
            get {
                return ResourceManager.GetString("game_text_ger_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schlag die
        ///Künstliche Intelligenz (KI) in der Hydrologie .
        /// </summary>
        public static string game_text_ger_gamename {
            get {
                return ResourceManager.GetString("game_text_ger_gamename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist nicht einfach, mit wenig Wasser hohe Erträge zu
        ///erreichen. Pflanzen reagieren im Laufe ihres Wachstums
        ///ganz unterschiedlich auf Trockenstress, Wetter und
        ///Bodenverhältnisse. Du kannst im Spiel .
        /// </summary>
        public static string game_text_ger_start {
            get {
                return ResourceManager.GetString("game_text_ger_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LET&apos;S PLAY.
        /// </summary>
        public static string play_eng {
            get {
                return ResourceManager.GetString("play_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOS GEHT&apos;S.
        /// </summary>
        public static string play_ger {
            get {
                return ResourceManager.GetString("play_ger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water consumption for the production of 100 grams of food.
        /// </summary>
        public static string table_description_eng {
            get {
                return ResourceManager.GetString("table_description_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasserverbrauch für die Produktion von je 100 Gramm Lebensmitteln.
        /// </summary>
        public static string table_description_ger {
            get {
                return ResourceManager.GetString("table_description_ger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LITRES PER INHABITANT.
        /// </summary>
        public static string water_eng_headline {
            get {
                return ResourceManager.GetString("water_eng_headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A water footprint is the total amount of water used by the 
        ///inhabitants of a country through the direct consumption of 
        ///drinking water and the indirect use of water for agricultural 
        ///or industrial products. When divided by the number of 
        ///inhabitants of the country, a personal water footprint emerges. 
        ///The global average is 1,240 cubic metres per capita and year. 
        ///In Germany, the consumption is 1,545 cubic metres, which 
        ///means 4,230 litres per day. The global water footprint is
        /// 7,450 billion cubic m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string water_eng_text {
            get {
                return ResourceManager.GetString("water_eng_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LITER PRO EINWOHNER.
        /// </summary>
        public static string water_ger_headline {
            get {
                return ResourceManager.GetString("water_ger_headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unter dem Wasserfußabdruck versteht man die gesamte 
        ///Wassermenge, die von den Einwohnern eines Landes 
        ///beansprucht wird – durch direkten Trinkwasserverbrauch 
        ///und die indirekte Nutzung von Wasser für landwirtschaftliche 
        ///oder industrielle Produkte. Umgerechnet auf die Zahl der 
        ///Einwohner/innen des Landes erhält man den persönlichen 
        ///Wasserfußabdruck. Der weltweite Durchschnittswert liegt bei 
        ///1.240 Kubikmeter pro Kopf und Jahr. In Deutschland sind es 
        ///1.545 Kubikmeter, das heißt 4.230 Liter pro Pers [rest of string was truncated]&quot;;.
        /// </summary>
        public static string water_ger_text {
            get {
                return ResourceManager.GetString("water_ger_text", resourceCulture);
            }
        }
    }
}
